version: '3.2'

services:
    db:
      build: ./db
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      networks:
        - back
      ports:
        - "${DB_PORT}:3306"
      volumes:
        - ./db/init:/docker-entrypoint-initdb.d
        - ./db/data:/var/lib/mysql
      working_dir: /var/lib/mysql
      command: --disable-partition-engine-check --innodb_use_native_aio=0
    php:
      build: ./php
      restart: unless-stopped
      networks:
        - front
        - back
      volumes:
        - ./php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini:ro
        - ${PHP_PROJECT_DIR}:/var/www/html
      working_dir: /var/www/html
    web:
      image: nginx:mainline-alpine
      restart: unless-stopped
      networks:
        - front
      ports:
        - "${WEB_PORT}:80"
      volumes:
        - ./web/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
        - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
        - ${PHP_PROJECT_DIR}/${WEBROOT_DIR}:/var/www/html/${WEBROOT_DIR}:ro
      working_dir: /var/www/html
      environment:
        WEBROOT_DIR: ${WEBROOT_DIR}
      command: /bin/sh -c "envsubst '$$WEBROOT_DIR' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    smtp:
      build: ./smtp
      restart: unless-stopped
      networks:
        - back
      ports:
        - "${MAILCATCHER_HTTP_PORT}:80"

networks:
  front:
  back:
